config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get :enter_passcode, to: 'welcome#enter_passcode'
  post :check_passcode, to: 'welcome#check_passcode'
  get :get_qr_code, to: 'welcome#get_qr_code'

  get :ep, to: 'welcome#enter_passcode'
  

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
require 'open-uri'

class Contact < ActiveRecord::Base
  has_attached_file :qr_code
  validates_attachment :qr_code, content_type: { content_type: /\Aimage\/.*\Z/ }

  validates_presence_of :phone_no, :serial_number, :bar_code
  before_create :validate_phone, if: "!phone_no.blank?"
  before_create :create_other_attributes
  before_create :generate_qrcode
  after_create :delete_temp_qrcode
  before_update :make_code_invalid

  def self.upload_csv(csv_data)
    CSV.foreach(csv_data.path, :headers => true, :header_converters => [:downcase]) do |row|
      self.create(phone_no: row["mobile number"], serial_number: row["serial number"], bar_code: row["bar code"])
    end
  end

  def self.upload_txt(txt_data)
    rows = txt_data.read.split("\n")
    rows.each do |row|
      data = row.split(",")
      self.create(phone_no: data[0].strip, bar_code: data[1].strip, serial_number: data[2].strip )
    end
  end

  def send_message(message)
    begin
      Client.messages.create(from: TWILIO_NUMBER, to: self.phone_no, body: message)
      self.sent_at = DateTime.now
      self.save
    rescue Twilio::REST::RequestError => e
      logger.error "error #{e}"
    end
  end

  def is_valid_url?
    !is_invalid
  end

  def regenerate_data()
    #self.passcode = Devise.friendly_token.first(8)
    #self.attempt_count = 0
    #self.is_invalid = false
    #self.save
  end

  rails_admin do
    create do
      field :phone_no
      field :bar_code
      field :serial_number
    end

    list do
      field :phone_no
      field :uuid
      field :passcode
      field :qr_code
      field :sent_at
    end
  end

  private

    def create_other_attributes
      #self.uuid = UUIDTools::UUID.random_create.to_s
      self.uuid = SecureRandom.urlsafe_base64(6)
      self.passcode = Devise.friendly_token.first(6)
    end

    def generate_qrcode
      #qr = RQRCode::QRCode.new( self.uuid, :size => 10, :level => :l )
      #png = qr.to_img
      #file_name = Rails.root.to_s + "/public/" + SecureRandom.hex(32) + ".png"
      #png.resize(90, 90).save(file_name)
      #file = File.open(file_name)
      #self.qr_code = file                                                    
      
      file_name = Rails.root.to_s + "/public/" + SecureRandom.hex(32) + ".png"      
      open(image_url(self.uuid, self.serial_number)) {|f|
        File.open(file_name, "wb") do |file|
          file.puts f.read          
        end         
      }     
      file = File.open(file_name) 
      self.qr_code = file
    end

    def image_url(code, serial_number)
      path = "http://qrickit.com/api/qr?d=#{code}&addtext=SERIAL+NUMBER:%20+#{serial_number}&txtcolor=000000&fgdcolor=000000&bgdcolor=ffffff&qrsize=300&t=p&e=m" 
      puts "Image URL: #{path}"
      return path
    end

    def delete_temp_qrcode
      #file_name = Rails.root.to_s + "/public/" + self.qr_code.original_filename
      #File.delete(file_name)
    end

    def make_code_invalid
      self.is_invalid = true if self.attempt_count == 10
    end

    def validate_phone
      if Phonie::Phone.parse self.phone_no
        self.phone_no = "+#{self.phone_no}" unless self.phone_no.include?('+')
      else
        self.errors.add(:phone_no, "#{self.phone_no} is not a valid number.")
        return false
      end
      true
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :get_contact, except: :index
  before_action :check_session, only: :get_qr_code

  def index
  end

  def enter_passcode
    raise ActiveRecord::RecordNotFound if @contact.blank?
  end

  def check_passcode
    if @contact.passcode == params[:passcode]
      @contact.update_attribute(:attempt_count, 0)
      gflash :success => "Congratulations! you have got your QR Code."
      session[:is_visited] = true
      redirect_to get_qr_code_path(uuid: @contact.uuid)
    else
      attempt_count = @contact.attempt_count.blank? ? 0 : @contact.attempt_count + 1
      @contact.update_attribute(:attempt_count, attempt_count)
      gflash :error => "Invalide passcode for given url."
      redirect_to enter_passcode_path(uuid: @contact.uuid)
    end
  end

  def get_qr_code
    session[:is_visited] = nil
  end

  private
    def check_session
      redirect_to enter_passcode_path(uuid: @contact.uuid) unless session[:is_visited]
    end

    def get_contact                                
      uuid = params[:u] || params[:uuid]
      @contact = Contact.find_by_uuid(uuid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/upload_phone_numbers.html.erb
<%= form_tag import_contact_path, multipart: true, class: "form-horizontal denser" do %>
    <fieldset>
      <div id="contact_file_field" class="control-group file_type file_field ">
        <label for="contact_contacts" class="control-label">Select File</label>
        <div class="controls">
          <%= file_field_tag :contacts, :accept => "text/csv" %>
          <p class="help-block">Only CSV or Text File allow.</p>
          <p class="help-block">Download <%= link_to "CSV", sample_file_path(:format => "csv") %> <%= link_to "Text", sample_file_path(:format => "txt") %> Sample file</p>
        </div>
      </div>
    </fieldset>
    <div class="form-actions">
      <%= button_tag(type: "submit", class: "btn btn-primary") do %>
        <i class="icon-white icon-ok"></i> Import
      <% end %>
      <span class="extra_buttons">
        <%= link_to '<i class="icon-remove"></i>Cancel'.html_safe, "/admin/contact", class: "btn" %>
      </span>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SMS Message" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%#= nav_bar :static => :top, :brand => "Rails Message", :responsive => true do %>
      <%#= menu_group do %>
          <%#= menu_item "Home", root_path %>
          <%#= menu_divider %>
          <%#= menu_item "About Us", "javascript:void(0)" %>
          <%#= menu_item "Contact", "javascript:void(0)" %>
      <%# end %>
      <%#= menu_group :pull => :right do %>
        <%#= menu_item "Log in as Admin", new_admin_user_session_path, :'data-no-turbolink' => false %>
      <%# end %>
    <%# end %>

    <%#= gflash %>

    <div class="container">
      <div class="row">
				<div class="col-md-2">&nbsp;</div>
				<div class="col-md-8"><%= yield %></div>
				<div class="col-md-2">&nbsp;</div>
      </div><!--/row-->
    </div> <!-- /container -->

    <!--<footer>-->
      <%#= nav_bar :static => :bottom do %>
        <!--<p>&copy; Company 2014</p>-->
      <%# end %>
    <!--</footer>-->
  </body>
</html>

app/views/welcome/_terms_and_conditions.erb
<p style="font-size: 11px">
	電子現金券受下列條款及細則約束。<br/>
	The eCoupon is bound by the below terms and conditions.
</p>                                                     
<br/>
<p style="font-size: 11px">
	電子現金券條款及細則<br/>
	Terms and conditions of eCoupon<br/>
	
	
	<ol style="font-size: 11px">
		<li>Pacific Coffee 8安士細杯裝手調飲品電子現金券(價值HK$29)(「電子現金券」)無論在任何情況下均不獲轉讓、撤銷、變更、退回或兌換現金。<br/>
	Pacific Coffee 8oz Short Size Handcrafted Beverages eCoupon (valued at HK$29) (the “eCoupon”) is not transferable and cannot be cancelled, altered, returnable or redeemed for cash under any circumstances.
		</li>

	 	<li>使用電子現金券時須受以下Pacific Coffee Company Ltd. 之條款及細則約束。<br/>
	The use of eCoupon is subject to the below Terms and Conditions of Pacific Coffee Company Ltd.
		</li>

		<li>在任何情況下，中國建設銀行(亞洲)股份有限公司不須亦不會對電子現金券之使用負任何責任。有關電子現金券之使用權利的任何爭議或投訴，均應與Pacific Coffee Company Ltd. 自行解決。<br/>
	China Construction Bank (Asia) Corporation Limited is not and will not be responsibility for any liabilities as regards the use of the eCoupon under all circumstances. Any disputes or complaints concerning the use of the eCoupon should be directed to Pacific Coffee Company Ltd.
		</li>
	</ol>
	<br/>	
	Pacific Coffee Company Ltd. 之條款及細則<br/>
	Terms and conditions of Pacific Coffee Company Ltd.<br/>
	
	
	<ol style="font-size: 11px">
		<li>電子現金券持有人可於任何手調飲品交易享有HK$29折扣優惠。<br/>
	The eCoupon entitles the holder of HK$29 discount on any purchase of handcrafted beverages.
  	</li> 
		<li>
	 電子現金券適用於Pacific Coffee Company各香港分店。<br/>
	The eCoupon is redeemable at all Pacific Coffee Company branches in Hong Kong.
  	</li>
		<li>
	 電子現金券不可與其他優惠同時使用 (自攜盛器優惠除外) 。<br/>
	The eCoupon cannot be redeemed in conjunction with any other promotions or privileges (except bring-your-own-mug offer).
		</li>
		<li>
	電子現金券只可使用一次。<br/>
	      The eCoupon is valid for one-time redemption only.
		</li>
		<li>
	請於2015年4月30日或之前使用電子現金券、逾期作廢。<br/>
	Please redeem the eCoupon on or before April 30, 2015; it will be invalid after the expiry date.
		</li>
		<li>
	Pacific Coffee Company Ltd將保留此電子現金券之最終決定權。<br/>
	Pacific Coffee Company Ltd. Reserves the right of final decision in case of any dispute arising from redemption of the eCoupon.	
		</li>
</p>

app/views/welcome/enter_passcode.html.erb
<img src="<%= image_path('logo.png') %>" alt="CCB (Asia)" width="auto" height="20"/>
<img src="<%= image_path('kv.jpg') %>" class="img-responsive" alt="CCB (Asia)" />
<% if @contact.is_valid_url? %>	
	<p style="font-size: 11px">
		感謝您過往對我們「網上銀行」服務的支持及使用。<br/>
		為表衷心的答謝，我們現奉上<strong style="color: #000">Pacific Coffee 8安士細杯裝手調飲品電子現金券</strong>，請悅納。
	</p>
   
	<p style="font-size: 10px">
	 Thank you for your continued support on using our Online Banking services.<br/>
	 We are pleased to offer you, our valuable customer, <strong style="color: #000">a Pacific Coffee 8oz Short Size Handcrafted Beverages eCoupon</strong> to show our sincere appreciation. Hope you will enjoy it.<br/>
	</p>	
	                                                                                       
	<p style="font-size: 10px">
		<strong style="color: #180090; font-size: 10px">請輸入經短訊接收的6位數字驗證碼以獲取電子現金券。</strong><br/>
	 	<strong style="color: #180090; font-size: 10px">Please enter 6 digit passcode received via SMS to get the eCoupon.</strong>
	</p>	
  <!--<p> Please enter the pass code to get the QR Code. <i>(A simple lead-in and instruction)</i> </p>-->

  <%= form_tag check_passcode_path, class: 'form-horizontal', id: 'check-form' do %>
    <center style="margin: 0 10px 0 10px">
			<div class="row">
	      <div class="form-group col-md-6">
	        <%= hidden_field_tag :uuid, @contact.uuid %>
	        <%= text_field_tag :passcode, "", placeholder: "", class: "form-control1" %>
	      </div>
			</div>
      <div class="form-group">
        <%= submit_tag "確認\nEnter", class: 'btn btn-primary' %>
      </div>
    </center>
  <% end %>
<% else %>
  <center style="margin: 0 10px 0 10px">
    <h4>You have 10 invalid attempts. This url is no longer valid for you.</h4>
  </center>
<% end %>
                                      
	<%= render 'terms_and_conditions' %>

<script>
   $(function() {

    // Setup form validation on the #register-form element
    $("#check-form").validate({

        // Specify the validation rules
        rules: {
            passcode: "required"
        },

        // Specify the validation error messages
        messages: {
            passcode: "Please enter your passcode"
        },

        submitHandler: function(form) {
            form.submit();
        }
    });

  });
</script>

app/views/welcome/get_qr_code.html.erb
<img src="<%= image_path('logo.png') %>" alt="CCB (Asia)" width="auto" height="20"/>
<img src="<%= image_path('kv.jpg') %>" class="img-responsive" alt="CCB (Asia)" />
<p style="color: #000; font-size: 12px">
	<span>
		<strong>
			Pacific Coffee 8安士細杯裝手調飲品電子現金券<br/>
			Pacific Coffee 8oz Short Size Handcrafted Beverages eCoupon
		</strong>
	</span>
	<center style="margin-top: 0px; z-index: -1">
		<img src="<%= @contact.qr_code.url %>" class="img-responsive" />
	  <%#= image_tag @contact.qr_code.url %>
	</center>
</p>

<center>
	<p style="font-size: 12px">
		請儲存此螢幕截圖以方便日後使用此電子現金券。<br/>
		To use this eCoupon at ease in the future, you are suggested to save this screenshot.
	</p>
</center>
<br/><br/>
<%= render 'terms_and_conditions' %>

app/views/welcome/invalid_url_info.html.erb
<center>
  <h4>The URL you are trying to access is not a valid URL.</h4>
</center>